#!/usr/bin/env bash
# Materialise + launch the six v0.3 re-validation arms (A..F), one per v6e-8.
#
# WHY THIS EXISTS
# ---------------
# docs/v0.3-reval-sweep-plan.md re-validates the frozen v0.3 recipe at a
# 5,000-step full-corpus horizon across SIX parallel single-host v6e-8 slices.
# The startup script runs exactly ONE config file per slice with no extra-args
# passthrough, so each arm needs a self-contained config. This script overlays
# the per-arm recipe knobs onto the base (configs/tpu/stage2_tpu_v6e8_reval.yaml),
# writes configs/tpu/reval/arm_<X>.yaml (committed as reproducible artifacts),
# and launches each via the existing launch_spot.sh (TRC_PROFILE=v6e-8-eu) with
# a distinct QR_NAME / NODE_ID. The launch path itself is UNCHANGED -- every arm
# is just a normal CONFIG_FILE run.
#
# The arm matrix below is the single source of truth for what differs per arm.
#
# Usage:
#   # 0. one-time: stage the full corpus to GCS (Phase 0c), then export its URI:
#   export SWEEP_DATA_GS_URI=gs://tinyaya-stage2-eu/data/full-corpus-YYYYMMDD.tar.gz
#
#   DRY_RUN=1 bash scripts/tpu/launch_reval_arms.sh        # just write the 6 configs
#   ARMS="A" bash scripts/tpu/launch_reval_arms.sh         # launch a single arm
#   bash scripts/tpu/launch_reval_arms.sh                  # write + launch all six
#
# Env:
#   ARMS               space/comma list of arm letters to act on (default: A B C D E F)
#   DRY_RUN=1          materialise configs only; do not create any QR
#   SWEEP_DATA_GS_URI  full-corpus tarball in GCS (forwarded to each slice; if
#                      unset each slice falls back to the full HF download)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BASE_CONFIG="$REPO_ROOT/configs/tpu/stage2_tpu_v6e8_reval.yaml"
OUT_DIR="$REPO_ROOT/configs/tpu/reval"

# ---- arm matrix: LETTER  r  lr_lora  exclude_top  dropout  wd  depth_unfreeze ----
# (dash '-' means "inherit the base value"). alpha is always 2*r (rsLoRA).
read -r -d '' ARM_MATRIX <<'EOF' || true
A 32 1.716e-4 2 0.05 0.01 0
B 64 1.2e-4   2 0.05 0.01 0
C 16 2.4e-4   2 0.05 0.01 0
D 32 1.716e-4 0 0.05 0.01 0
E 32 1.716e-4 2 0.10 0.05 0
F 32 1.716e-4 2 0.05 0.01 2
EOF

WANT="${ARMS:-A B C D E F}"
WANT="${WANT//,/ }"

mkdir -p "$OUT_DIR"

want_arm() {
    local a="$1"
    for w in $WANT; do [ "$w" = "$a" ] && return 0; done
    return 1
}

while read -r LETTER R LR EXCL DROP WD DUNF; do
    [ -z "${LETTER:-}" ] && continue
    want_arm "$LETTER" || continue

    arm_config="$OUT_DIR/arm_${LETTER}.yaml"
    # Overlay the arm knobs onto the base via an in-place YAML edit. Python (not
    # sed) so nested keys are set unambiguously and alpha stays 2*r.
    BASE_CONFIG="$BASE_CONFIG" ARM_CONFIG="$arm_config" \
    LETTER="$LETTER" R="$R" LR="$LR" EXCL="$EXCL" DROP="$DROP" WD="$WD" DUNF="$DUNF" \
    python3 - <<'PY'
import os
import yaml

with open(os.environ["BASE_CONFIG"]) as f:
    cfg = yaml.safe_load(f)

letter = os.environ["LETTER"]
r = int(os.environ["R"])
cfg["lora"]["r"] = r
cfg["lora"]["alpha"] = 2 * r  # rsLoRA convention
cfg["lora"]["dropout"] = float(os.environ["DROP"])
cfg["lora"]["lora_exclude_top"] = int(os.environ["EXCL"])
cfg["lora"]["depth_unfreeze_blocks"] = int(os.environ["DUNF"])
cfg["optim"]["lr_lora"] = float(os.environ["LR"])
cfg["train"]["weight_decay"] = float(os.environ["WD"])
cfg["logging"]["save_dir"] = f"gs://tinyaya-stage2-eu/checkpoints/stage2-reval-5k/arm_{letter}"
cfg["logging"]["wandb_run_name"] = f"v03-reval-arm_{letter}"
cfg["logging"]["wandb_group"] = "v03-5k-reval"

with open(os.environ["ARM_CONFIG"], "w") as f:
    f.write(f"# GENERATED by scripts/tpu/launch_reval_arms.sh -- arm {letter}.\n")
    f.write("# Edit the ARM_MATRIX in that script + regenerate; do not hand-edit.\n")
    yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
print(f"[reval] wrote {os.environ['ARM_CONFIG']}  (r={r} lr={os.environ['LR']} "
      f"excl={os.environ['EXCL']} drop={os.environ['DROP']} wd={os.environ['WD']} "
      f"depth_unfreeze={os.environ['DUNF']})")
PY

    if [ "${DRY_RUN:-0}" = "1" ]; then
        continue
    fi

    rel_config="configs/tpu/reval/arm_${LETTER}.yaml"
    qr="tinyaya-reval-arm-${LETTER,,}-qr"
    node="tinyaya-reval-arm-${LETTER,,}"
    echo "==> launching reval arm $LETTER"
    echo "    config: $rel_config"
    echo "    QR/node: $qr / $node"
    echo "    SWEEP_DATA_GS_URI=${SWEEP_DATA_GS_URI:-<unset: full HF download>}"
    TRC_PROFILE=v6e-8-eu \
    CONFIG_FILE="$rel_config" \
    QR_NAME="$qr" \
    NODE_ID="$node" \
    SWEEP_DATA_GS_URI="${SWEEP_DATA_GS_URI:-}" \
        bash "$SCRIPT_DIR/launch_spot.sh"
done <<< "$ARM_MATRIX"

echo "==> done. Watch an arm with:  QR_NAME=tinyaya-reval-arm-a-qr bash scripts/tpu/ops.sh status"
